create table banks_table
(
    id   bigint generated by default as identity (start with 1),
    name varchar(255) not null,
    primary key (id)
);
create table clients_table
(
    id         bigint generated by default as identity (start with 1),
    email      varchar(255) not null,
    first_name varchar(255) not null,
    last_name  varchar(255) not null,
    passport   bigint       not null,
    phone      bigint       not null,
    bank_id    bigint,
    primary key (id)
);
create table credits_table
(
    id            bigint generated by default as identity (start with 1),
    interest_rate double  not null,
    limit         integer not null,
    bank_id       bigint,
    primary key (id)
);
create table offers_table
(
    id          bigint generated by default as identity (start with 1),
    credit_sum  integer not null,
    credit_term integer not null,
    client_id   bigint,
    credit_id   bigint,
    primary key (id)
);
create table payments_table
(
    id                 bigint generated by default as identity (start with 1),
    credit_body_sum    double not null,
    credit_percent_sum double not null,
    payment_date       date,
    payment_sum        double not null,
    offer_id           bigint,
    primary key (id)
);
alter table clients_table
    add constraint FK75m9t0v6p4eq1kiwuvxedyuf2 foreign key (bank_id) references banks_table;
alter table credits_table
    add constraint FKk43nmjww7rhqf3eu7h2mudwem foreign key (bank_id) references banks_table;
alter table offers_table
    add constraint FKlbvggcc9b6wnm1qe7xby9mta9 foreign key (client_id) references clients_table;
alter table offers_table
    add constraint FKmbrijrf2384ml3rp6u4clxw88 foreign key (credit_id) references credits_table;
alter table payments_table
    add constraint FKoouhe4hvh6jmrp5ru34t8ct8y foreign key (offer_id) references offers_table;